///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAsset {
  AppAsset._();

  static const String iconsAlert = 'assets/icons/alert.svg';
  static const String iconsArrowDown = 'assets/icons/arrow_down.svg';
  static const String iconsBell = 'assets/icons/bell.svg';
  static const String iconsCoin = 'assets/icons/coin.svg';
  static const String iconsFamily = 'assets/icons/family.svg';
  static const String iconsLogo = 'assets/icons/logo.svg';
  static const String iconsRightArrow = 'assets/icons/right_arrow.svg';
  static const String imagesAlert = 'assets/images/alert.png';
  static const String imagesBanner0 = 'assets/images/banner_0.png';
  static const String imagesBell = 'assets/images/bell.png';
  static const String imagesCalculator = 'assets/images/calculator.png';
  static const String imagesCoin = 'assets/images/coin.png';
  static const String imagesFamily = 'assets/images/family.png';
  static const String imagesHoldingMoney = 'assets/images/holding_money.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesShowCard = 'assets/images/show_card.png';
  static const String imagesTalk = 'assets/images/talk.png';
  static const String pretendardPretendardBold =
      'assets/fonts/pretendard/Pretendard-Bold.otf';
  static const String pretendardPretendardMedium =
      'assets/fonts/pretendard/Pretendard-Medium.otf';
  static const String pretendardPretendardRegular =
      'assets/fonts/pretendard/Pretendard-Regular.otf';
  static const String pretendardPretendardSemiBold =
      'assets/fonts/pretendard/Pretendard-SemiBold.otf';
}
